data = {
    "The 1975": {
        "The 1975": ["The 1975", "Settle Down"],
        "I Like It When You Sleep, for You Are So Beautiful Yet So Unaware of It": [
            "A Change of Heart",
            "Paris",
        ],
        "Notes on a Conditional Form": ["Roadkill", "Frail State of Mind"],
        "Being Funny in a Foreign Language": ["Happiness", "Part of the Band"],
    },
    "Alvvays": {
        "Alvvays": ["Adult Diversion", "Archie, Marry Me"],
        "Antisocialites": ["In Undertow", "Dreams Tonite"],
        "Blue Rev": ["Pharmacist", "Easy On Your Own"],
    },
    "The Japanese House": {
        "Good at Falling": ["Lilo", "Maybe You’re the Reason"],
        "Chewing Cotton Wool": ["Chewing Cotton Wool"],
        "In the End It Always Does": ["Boyhood", "Sunshine Baby"],
    },
    "The Strokes": {
        "Is This It": ["Someday", "Last Nite"],
        "Room on Fire": ["Reptilia", "Under Control"],
        "First Impressions of Earth": ["Juicebox", "Heart in a Cage"],
        "The New Abnormal": ["Bad Decisions", "At the Door", "Selfless"],
    },
    "Flipturn": {
        "Citrona": ["August", "Six Below", "Fletcher"],
        "Heavy Colors": ["Vanilla", "Chicago"],
        "Shadowglow": ["Playground", "Hollow", "Whales"],
    },
    "Clairo": {
        "Immunity": ["Bags", "Sofia"],
        "Sling": ["Amoeba", "Blouse"],
        "Charm": ["Juna", "Thank You", "Terrapin"],
    },
    "Quarters of Change": {
        "Into The Rift": ["T Love", "Chloe", "Dead", "Jaded", "Ms. Dramatic"],
        "Portraits": ["Heaven Bound", "Cherry Tree", "Illogical Decisions"],
    },
    "Phoebe Bridgers": {
        "Stranger in the Alps": ["Motion Sickness"],
        "Punisher": ["Kyoto"],
    },
    "Gregory Alan Isakov": {"That Sea, The Gambler": ["All There Is"]},
    "Minova": {"Stranger": ["Stranger"]},
    "Abby Holliday": {"CRACK A SMILE COME ON STAY A WHILE": ["The Price"]},
    "Charli XCX": {"Brat": ["Club Classics"]},
    "Porter Robinson": {"SMILE! :D": ["Cheerleader"]},
    "Clean Spill": {"Note to Self": ["Note to Self"]},
    "The Backseat Lovers": {"Out of Tune": ["Out of Tune"]},
    "Rubblebucket": {"Rubblebucket": ["Bikes"]},
    "Jelani Aryeh": {"Stella Brown": ["Stella Brown"]},
    "Maya Hawke": {"MOSS": ["Backup Plan"]},
    "Young the Giant": {"Young The Giant": ["Cough Syrup"]},
    "Men I Trust": {"Show Me How": ["Show Me How"]},
    "benches": {"Wishful Thinking (At Its Best)": ["Queen of Hearts"]},
    "Better Than This": {"Dance Party": ["Dance Party"]},
    "The Moss": {"Insomnia EP": ["Carousel"]},
    "Mamalarky": {"Mamalarky": ["You Make Me Smile"]},
    "Bleachers": {"Modern Girl": ["Modern Girl"]},
    "Freak Slug": {"Radio": ["Radio"]},
    "Maximo Park": {"Our Earthly Pleasures": ["Books From Boxes"]},
    "Alice Phoebe Lou": {"Shelter": ["Open My Door"]},
    "Sea Lemon": {"Close Up": ["Eraser"]},
    "Djo": {"DECIDE": ["End of Beginning"]},
}
